### ISSUE TITLE
API Search Functionality

### ISSUE THREAD

**Issue by raneem-yad** [raneem-yad/wissen#3]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Search Functionality |
| Epic | Course Discovery and Filtering |
| User Story | API Development for Search |

## Description
**As a** Backend developer, **I want** develop APIs for searching, **So that** I provide users with a seamless browsing experience.

## Acceptance Criteria
1. The API should include endpoints for searching across different types of data, such as courses.
2. Implement search functionality that supports keyword-based search queries.
3. Implement pagination to handle large result sets efficiently and improve performance.

## Tasks
- [ ] Design API endpoints for searching across different types of data.
- [ ] Implement keyword-based search functionality.
- [ ] Implement pagination to handle large result sets efficiently.
