### ISSUE TITLE
API Development for User Profiles

### ISSUE THREAD

**Issue by raneem-yad** [raneem-yad/wissen#7]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Profile Management |
| Epic | Profile Pages |
| User Story | API Development for User Profiles |

## Description
**As a** backend developer, **I want** to create APIs for user profiles, **So that** user account information can be efficiently managed, including retrieval, and updating user data.

## Acceptance Criteria
1. The API should include endpoints for retrieving user profiles, updating user information user accounts.
2. Implement functionality to retrieve user information such as username, email, profile picture, and other relevant details.
3. Enable users to update their profile information, including username, email, and profile picture.

## Tasks
- [ ] Design API endpoints for retrieving user profiles, updating user information, and deleting user accounts.
- [ ]  Implement functionality to retrieve user information such as username, email, profile picture, etc.
- [ ] Develop mechanisms to allow users to update their profile information.
